Update chocolatine.yml

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -13,87 +13,82 @@ env:
   EXECUTABLES: ${{ vars.EXECUTABLES }}
   
 jobs:
-  check_repository:
-    runs-on: ubuntu-latest
-    outputs:
-      is_mirror: ${{ steps.check.outputs.is_mirror }}
-    steps:
-      - id: check
-        run: |
-          if [ "${{ github.event.repository.ssh_url }}" == "${{ env.MIRROR_SSH_URL }}" ]; then
-            echo "is_mirror=true" >> "$GITHUB_OUTPUT"
-          else
-            echo "is_mirror=false" >> "$GITHUB_OUTPUT"
-          fi
-
   check_compilation_and_coding_style:
-    needs: check_repository
-    if: needs.check_repository.outputs.is_mirror == 'false'
     runs-on: ubuntu-latest
+    if: ${{ !contains($MIRROR_SSH_URL, github.repository) }}
     container: epitechcontent/epitest-docker
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
+        with:
+          fetch-depth: 1
 
-      - name: Launch coding style checker
+      - name: Check coding style
         run: banana-check-repo
 
-      - name: Compile project
-        run: make
+      - name: Check compilation
+        run: make 2>&1 | tee output.txt
+        timeout-minutes: 2
         env:
           CC: epiclang
-        timeout-minutes: 2
 
-      - name: Display coding style errors
+      - name: List coding style errors
         run: |
-          if [ -s coding-style-reports.log ]; then
-            while IFS= read -r line; do
-              FILE=$(echo "$line" | cut -d':' -f1 | xargs)
-              LINE=$(echo "$line" | cut -d':' -f2 | xargs)
-              SEVERITY=$(echo "$line" | cut -d':' -f3 | xargs)
-              ERROR=$(echo "$line" | cut -d':' -f4 | xargs)
-              echo "::error file=$FILE,line=$LINE,title=$SEVERITY coding style error::$ERROR"
-            done < coding-style-reports.log
+          grep "\[Banana\]" output.txt | while read line
+          do
+            file=$(echo "$line" | cut -d: -f1)
+            row=$(echo "$line" | cut -d: -f2)
+            column=$(echo "$line" | cut -d: -f3)
+            mess=$(echo "$line" | cut -d: -f5-)
+            echo "::error file=$file,line=$row,col=$column::$mess"
+          done
+
+      - name: Job fail
+        run: |
+          if grep -q "\[Banana\]" output.txt; then
             exit 1
           fi
 
-      - name: Clean project
+      - name: Clean
         run: make clean
 
-      - name: Verify executables
-        shell: bash
+      - name: Check Executables environment variable
         run: |
-          IFS=',' read -ra EXES <<< "$EXECUTABLES"
-          for exe in "${EXES[@]}"; do
-            if [ ! -f "$exe" ] || [ ! -x "$exe" ]; then
-              echo "::error title=Executable missing or not executable::$exe is missing or cannot be executed."
-              exit 1
-            fi
+          IFS=','
+          for executable in $EXECUTABLES
+          do
+          if [ ! -f "$executable" ] || [ ! -x "$executable" ]; then
+          echo "::error::$executable is not executable or missing"
+          exit 1
+          fi
           done
 
   run_tests:
-    needs: check_compilation_and_coding_style
     runs-on: ubuntu-latest
+    needs: check_compilation_and_coding_style
+    if: ${{ !contains(vars.MIRROR_REPO, github.repository) }}
     container: epitechcontent/epitest-docker
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
+        with:
+          fetch-depth: 1
 
       - name: Run tests
         run: make tests_run
         timeout-minutes: 2
 
   push_to_mirror:
-    needs: run_tests
-    if: github.event_name == 'push'
     runs-on: ubuntu-latest
+    needs: run_tests
+    if: ${{ !contains(vars.MIRROR_REPO, github.repository) && github.event_name == 'push'}}
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v5
         with:
           fetch-depth: 0
 
-      - name: Push to mirror
+      - name: Mirror to epitech repo
         uses: pixta-dev/repository-mirroring-action@v1
         with:
           target_repo_url: ${{ env.MIRROR_SSH_URL }}
